coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 20%
        base: auto
        # advanced
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null
    patch: off

codecov:
  token: 76e60493-1dd4-46b5-9824-c50b466141b6 